from collections import OrderedDict

#
#   Type Definitions:
#
#   Stamp - Stamp collected from completing some task in a sport
#   Hard Stamp - Stamp that is deemed too hard for casuals to reliably get. These can be removed in logic in settings
#   Long Stamp - Stamp that is deemed too much of a grind to get. These can be removed in logic in settings
#
#   Pro Status - Getting pro status in a sport
#   Champion - Beating the champion in a sport
#   Difficulty - Unlocking the next difficulty in a sport
#   Level - Unlocking the next level in a sport.
# 
#   iPoint - I-Point in Island Flyover (only half ever required)
#   Balloon - White Balloon in Island Flyover (only half ever required)
#
#   Custom - Custom locations added for the randomizer. Example could be getting your first win in Speed Slice
#


#       Location:                                             Type                 Category ID    Sport ID                Location ID        
location_table = OrderedDict([
    #Swordplay Duel
    ("Swordplay Duel - First Win",                            ('Custom',            1,             1,                      0x0000)),
    ("Swordplay Duel (Stamp) - Cliff-hanger",                 ('Stamp',             1,             1,                      0x0001)),
    ("Swordplay Duel (Stamp) - Straight to the Point",        ('Stamp',             1,             1,                      0x0002)),
    ("Swordplay Duel (Stamp) - Met Your Match",               ('Stamp',             1,             1,                      0x0003)),
    ("Swordplay Duel (Stamp) - One-Hit Wonder",               ('Stamp',             1,             1,                      0x0004)),
    ("Swordplay Duel (Stamp) - Last Mii Standing",            ('Impossible Stamp',  1,             1,                      0x0005)),
    ("Swordplay Duel - Pro Status",                           ('Pro Status',        1,             1,                      0x0006)),
    ("Swordplay Duel - Beat The Champion (Matt)",             ('Champion',          1,             1,                      0x0007)), 
    #Swordplay Speed Slice
    ("Swordplay Speed Slice - First Win",                     ('Custom',            1,             2,                      0x0008)),
    ("Swordplay Speed Slice (Stamp) - Slice and Dice",        ('Stamp',             1,             2,                      0x0009)),
    ("Swordplay Speed Slice (Stamp) - Slicing Machine",       ('Stamp',             1,             2,                      0x000A)),
    ("Swordplay Speed Slice (Stamp) - Psychic Slice",         ('Stamp',             1,             2,                      0x000B)),
    ("Swordplay Speed Slice (Stamp) - Double Time",           ('Stamp',             1,             2,                      0x000C)),
    ("Swordplay Speed Slice (Stamp) - A Cut Above",           ('Impossible Stamp',  1,             2,                      0x000D)),
    ("Swordplay Speed Slice - Pro Status",                    ('Pro Status',        1,             2,                      0x000E)),
    ("Swordplay Speed Slice - Beat The Champion (Matt)",      ('Champion',          1,             2,                      0x000F)),
    #Swordplay Showdown
    ("Swordplay Showdown - Complete Stage 1",                 ('Custom',            1,             3,                      0x0010)),
    ("Swordplay Showdown - Complete Stage 2",                 ('Custom',            1,             3,                      0x0011)),
    ("Swordplay Showdown - Complete Stage 3",                 ('Custom',            1,             3,                      0x0012)),
    ("Swordplay Showdown - Complete Stage 4",                 ('Custom',            1,             3,                      0x0013)),
    ("Swordplay Showdown - Complete Stage 5",                 ('Custom',            1,             3,                      0x0014)),
    ("Swordplay Showdown - Complete Stage 6",                 ('Custom',            1,             3,                      0x0015)),
    ("Swordplay Showdown - Complete Stage 7",                 ('Custom',            1,             3,                      0x0016)),
    ("Swordplay Showdown - Complete Stage 8",                 ('Custom',            1,             3,                      0x0017)),
    ("Swordplay Showdown - Complete Stage 9",                 ('Custom',            1,             3,                      0x0018)),
    ("Swordplay Showdown - Complete Stage 10",                ('Custom',            1,             3,                      0x0019)),
    ("Swordplay Showdown - Complete Stage 11",                ('Custom',            1,             3,                      0x001A)),
    ("Swordplay Showdown - Complete Stage 12",                ('Custom',            1,             3,                      0x001B)),
    ("Swordplay Showdown - Complete Stage 13",                ('Custom',            1,             3,                      0x001C)),
    ("Swordplay Showdown - Complete Stage 14",                ('Custom',            1,             3,                      0x001D)),
    ("Swordplay Showdown - Complete Stage 15",                ('Custom',            1,             3,                      0x001E)),
    ("Swordplay Showdown - Complete Stage 16",                ('Custom',            1,             3,                      0x001F)),
    ("Swordplay Showdown - Complete Stage 17",                ('Custom',            1,             3,                      0x0020)),
    ("Swordplay Showdown - Complete Stage 18",                ('Custom',            1,             3,                      0x0021)),
    ("Swordplay Showdown - Complete Stage 19",                ('Custom',            1,             3,                      0x0022)),
    ("Swordplay Showdown - Complete Stage 20",                ('Custom',            1,             3,                      0x0023)),
    ("Swordplay Showdown (Stamp) - Not a Scratch",            ('Stamp',             1,             3,                      0x0024)),
    ("Swordplay Showdown (Stamp) - Sword Fighter",            ('Long Stamp',        1,             3,                      0x0025)),
    ("Swordplay Showdown (Stamp) - Perfect 10",               ('Hard Stamp',        1,             3,                      0x0026)),
    ("Swordplay Showdown (Stamp) - Swordmaster",              ('Long Stamp',        1,             3,                      0x0027)),
    ("Swordplay Showdown (Stamp) - Untouchable",              ('Impossible Stamp',  1,             3,                      0x0028)),
    ("Swordplay Showdown - Pro Status",                       ('Pro Status',        1,             3,                      0x0029)),
    #Wakeboarding
    ("Wakeboarding (Stamp) - Huge Air",                       ('Stamp',             2,             4,                      0x002A)),
    ("Wakeboarding (Stamp) - Bag of Tricks",                  ('Stamp',             2,             4,                      0x002B)),
    ("Wakeboarding (Stamp) - Smooth Landing",                 ('Stamp',             2,             4,                      0x002C)),
    ("Wakeboarding (Stamp) - Master Carver",                  ('Stamp',             2,             4,                      0x002D)),
    ("Wakeboarding (Stamp) - The Long Way Home",              ('Stamp',             2,             4,                      0x002E)),
    ("Wakeboarding - Pro Status",                             ('Pro Status',        2,             4,                      0x002F)),
    #Frisbee Dog
    ("Frisbee Dog (Stamp) - Good Dog",                        ('Stamp',             3,             5,                      0x0030)),
    ("Frisbee Dog (Stamp) - Balloon Animal",                  ('Stamp',             3,             5,                      0x0031)),
    ("Frisbee Dog (Stamp) - A for Effort",                    ('Hard Stamp',        3,             5,                      0x0032)),
    ("Frisbee Dog (Stamp) - Perfect Target",                  ('Hard Stamp',        3,             5,                      0x0033)),
    ("Frisbee Dog (Stamp) - Golden Arm",                      ('Hard Stamp',        3,             5,                      0x0034)),
    ("Frisbee Dog - Pro Status",                              ('Pro Status',        3,             5,                      0x0035)),
    #Frisbee Golf
    ("Frisbee Golf - Complete Hole 1",                        ('Custom',            3,             6,                      0x0036)),
    ("Frisbee Golf - Complete Hole 2",                        ('Custom',            3,             6,                      0x0037)),
    ("Frisbee Golf - Complete Hole 3",                        ('Custom',            3,             6,                      0x0038)),
    ("Frisbee Golf - Complete Hole 4",                        ('Custom',            3,             6,                      0x0039)),
    ("Frisbee Golf - Complete Hole 5",                        ('Custom',            3,             6,                      0x003A)),
    ("Frisbee Golf - Complete Hole 6",                        ('Custom',            3,             6,                      0x003B)),
    ("Frisbee Golf - Complete Hole 7",                        ('Custom',            3,             6,                      0x003C)),
    ("Frisbee Golf - Complete Hole 8",                        ('Custom',            3,             6,                      0x003D)),
    ("Frisbee Golf - Complete Hole 9",                        ('Custom',            3,             6,                      0x003E)),
    ("Frisbee Golf - Complete Hole 10",                       ('Custom',            3,             6,                      0x003F)),
    ("Frisbee Golf - Complete Hole 11",                       ('Custom',            3,             6,                      0x0040)),
    ("Frisbee Golf - Complete Hole 12",                       ('Custom',            3,             6,                      0x0041)),
    ("Frisbee Golf - Complete Hole 13",                       ('Custom',            3,             6,                      0x0042)),
    ("Frisbee Golf - Complete Hole 14",                       ('Custom',            3,             6,                      0x0043)),
    ("Frisbee Golf - Complete Hole 15",                       ('Custom',            3,             6,                      0x0044)),
    ("Frisbee Golf - Complete Hole 16",                       ('Custom',            3,             6,                      0x0045)),
    ("Frisbee Golf - Complete Hole 17",                       ('Custom',            3,             6,                      0x0046)),
    ("Frisbee Golf - Complete Hole 18",                       ('Custom',            3,             6,                      0x0047)),
    ("Frisbee Golf - Complete Hole 19",                       ('Custom',            3,             6,                      0x0048)),
    ("Frisbee Golf - Complete Hole 20",                       ('Custom',            3,             6,                      0x0049)),
    ("Frisbee Golf - Complete Hole 21",                       ('Custom',            3,             6,                      0x004A)),            
    ("Frisbee Golf - Get a par",                              ('Custom',            3,             6,                      0x004B)),
    ("Frisbee Golf - Get a birdie",                           ('Custom',            3,             6,                      0x004C)),
    ("Frisbee Golf - Get an eagle",                           ('Custom',            3,             6,                      0x004D)),
    ("Frisbee Golf (Stamp) - Under Par",                      ('Stamp',             3,             6,                      0x004E)),
    ("Frisbee Golf (Stamp) - Lucky Skip",                     ('Stamp',             3,             6,                      0x004F)),
    ("Frisbee Golf (Stamp) - On a Roll",                      ('Hard Stamp',        3,             6,                      0x0050)),
    ("Frisbee Golf (Stamp) - Hole in One",                    ('Stamp',             3,             6,                      0x0051)),
    ("Frisbee Golf (Stamp) - Straight and Narrow",            ('Impossible Stamp',  3,             6,                      0x0052)),
    ("Frisbee Golf - Pro Status",                             ('Pro Status',        3,             6,                      0x0053)), 
    #Archery
    ("Archery (Stamp) - Bull Stampede",                       ('Stamp',             4,             7,                      0x0054)),
    ("Archery (Stamp) - Sure Shot",                           ('Stamp',             4,             7,                      0x0055)),
    ("Archery (Stamp) - Century Shot",                        ('Long Stamp',        4,             7,                      0x0056)),
    ("Archery (Stamp) - A Secret to Everybody",               ('Hard Stamp',        4,             7,                      0x0057)),
    ("Archery (Stamp) - Sharpshooter",                        ('Impossible Stamp',  4,             7,                      0x0058)),
    ("Archery - Pro Status",                                  ('Pro Status',        4,             7,                      0x0059)),
    #Basketball 3-Point Contest
    ("3-Point Contest (Stamp) - Hot Streak",                  ('Stamp',             5,             8,                      0x005A)),
    ("3-Point Contest (Stamp) - Bonus Plumber",               ('Stamp',             5,             8,                      0x005B)),
    ("3-Point Contest (Stamp) - Quick Draw",                  ('Hard Stamp',        5,             8,                      0x005C)),
    ("3-Point Contest (Stamp) - Hot Hand",                    ('Impossible Stamp',  5,             8,                      0x005D)),
    ("3-Point Contest (Stamp) - Pure Shooter",                ('Impossible Stamp',  5,             8,                      0x005E)),
    ("3-Point Contest - Pro Status",                          ('Pro Status',        5,             8,                      0x005F)),
    #Basketball Pickup Game
    ("Pickup Game (Stamp) - Triple Dip",                      ('Stamp',             5,             9,                      0x0060)),
    ("Pickup Game (Stamp) - Rim Rattler",                     ('Stamp',             5,             9,                      0x0061)),
    ("Pickup Game (Stamp) - Lights Out",                      ('Hard Stamp',        5,             9,                      0x0062)),
    ("Pickup Game (Stamp) - Buzzer Beater",                   ('Hard Stamp',        5,             9,                      0x0063)),
    ("Pickup Game (Stamp) - Hoop Hero",                       ('Impossible Stamp',  5,             9,                      0x0064)),
    ("Pickup Game - Pro Status",                              ('Pro Status',        5,             9,                      0x0065)),
    ("Pickup Game (Stamp) - Beat The Champion (Tommy)",       ('Champion',          5,             9,                      0x0066)),
    #Table Tennis
    ("Table Tennis Match (Stamp) - In Your Face",             ('Stamp',             6,             10,                     0x0067)),
    ("Table Tennis Match (Stamp) - Back from the Brink",      ('Hard Stamp',        6,             10,                     0x0068)),
    ("Table Tennis Match (Stamp) - Epic Rally",               ('Hard Stamp',        6,             10,                     0x0069)),
    ("Table Tennis Match (Stamp) - Perfectly Matched",        ('Hard Stamp',        6,             10,                     0x006A)),
    ("Table Tennis Match (Stamp) - Table Titan",              ('Impossible Stamp',  6,             10,                     0x006B)),
    ("Table Tennis Match - Pro Status",                       ('Pro Status',        6,             10,                     0x006C)),
    ("Table Tennis Match - Beat The Champion (Lucia)",        ('Champion',          6,             10,                     0x006D)),
    #Table Tennis Return Challenge
    ("Return Challenge (Stamp) - 50-pointer",                 ('Stamp',             6,             11,                     0x006E)),
    ("Return Challenge (Stamp) - 100-pointer",                ('Hard Stamp',        6,             11,                     0x006F)),
    ("Return Challenge (Stamp) - 200-pointer",                ('Impossible Stamp',  6,             11,                     0x0070)),
    ("Return Challenge (Stamp) - Recycler",                   ('Impossible Stamp',  6,             11,                     0x0071)),
    ("Return Challenge (Stamp) - Save Face",                  ('Impossible Stamp',  6,             11,                     0x0072)),
    ("Return Challenge - Pro Status",                         ('Pro Status',        6,             11,                     0x0073)),
    #Golf
    ("Golf - Complete Hole 1",                                ('Custom',            7,             12,                     0x0074)),
    ("Golf - Complete Hole 2",                                ('Custom',            7,             12,                     0x0075)),
    ("Golf - Complete Hole 3",                                ('Custom',            7,             12,                     0x0076)),
    ("Golf - Complete Hole 4",                                ('Custom',            7,             12,                     0x0077)),
    ("Golf - Complete Hole 5",                                ('Custom',            7,             12,                     0x0078)),
    ("Golf - Complete Hole 6",                                ('Custom',            7,             12,                     0x0079)),
    ("Golf - Complete Hole 7",                                ('Custom',            7,             12,                     0x007A)),
    ("Golf - Complete Hole 8",                                ('Custom',            7,             12,                     0x007B)),
    ("Golf - Complete Hole 9",                                ('Custom',            7,             12,                     0x007C)),
    ("Golf - Complete Hole 10",                               ('Custom',            7,             12,                     0x007D)),
    ("Golf - Complete Hole 11",                               ('Custom',            7,             12,                     0x007E)),
    ("Golf - Complete Hole 12",                               ('Custom',            7,             12,                     0x007F)),
    ("Golf - Complete Hole 13",                               ('Custom',            7,             12,                     0x0080)),
    ("Golf - Complete Hole 14",                               ('Custom',            7,             12,                     0x0081)),
    ("Golf - Complete Hole 15",                               ('Custom',            7,             12,                     0x0082)),
    ("Golf - Complete Hole 16",                               ('Custom',            7,             12,                     0x0083)),
    ("Golf - Complete Hole 17",                               ('Custom',            7,             12,                     0x0084)),
    ("Golf - Complete Hole 18",                               ('Custom',            7,             12,                     0x0085)),
    ("Golf - Complete Hole 19",                               ('Custom',            7,             12,                     0x0086)),
    ("Golf - Complete Hole 20",                               ('Custom',            7,             12,                     0x0087)),
    ("Golf - Complete Hole 21",                               ('Custom',            7,             12,                     0x0088)),
    ("Golf - Par",                                            ('Custom',            7,             12,                     0x0089)),
    ("Golf - Birdie",                                         ('Custom',            7,             12,                     0x008A)),
    ("Golf - Eagle",                                          ('Custom',            7,             12,                     0x008B)),
    ("Golf (Stamp) - Under Par",                              ('Stamp',             7,             12,                     0x008C)),
    ("Golf (Stamp) - Chip In",                                ('Stamp',             7,             12,                     0x008D)),
    ("Golf (Stamp) - King of Clubs",                          ('Hard Stamp',        7,             12,                     0x008E)),
    ("Golf (Stamp) - Ace of Clubs",                           ('Impossible Stamp',  7,             12,                     0x008F)),
    ("Golf (Stamp) - Hole in One",                            ('Impossible Stamp',  7,             12,                     0x0090)),
    ("Golf - Pro Status",                                     ('Pro Status',        7,             12,                     0x0091)),         
    #Bowling 10 Pin
    ("Bowling 10 Pin - First Strike",                         ('Custom',            8,             13,                     0x0092)),
    ("Bowling Standard (Stamp) - Gobble Gobble",              ('Stamp',             8,             13,                     0x0093)),
    ("Bowling Standard (Stamp) - Split Spare",                ('Stamp',             8,             13,                     0x0094)),
    ("Bowling Standard (Stamp) - High Roller",                ('Hard Stamp',        8,             13,                     0x0095)),
    ("Bowling Standard (Stamp) - Pin Dropper",                ('Hard Stamp',        8,             13,                     0x0096)),
    ("Bowling Standard (Stamp) - Perfect Game",               ('Impossible Stamp',  8,             13,                     0x0097)),
    ("Bowling Standard - Pro Status",                         ('Pro Status',        8,             13,                     0x0098)),      
    #Bowling 100 Pin
    ("Bowling 100-Pin - First Strike",                        ('Custom',            8,             14,                     0x0099)),
    ("Bowling 100-Pin (Stamp) - Super Strike",                ('Stamp',             8,             14,                     0x009A)),
    ("Bowling 100-Pin (Stamp) - Split Spare",                 ('Stamp',             8,             14,                     0x009B)),
    ("Bowling 100-Pin (Stamp) - Off the Wall",                ('Stamp',             8,             14,                     0x009C)),
    ("Bowling 100-Pin (Stamp) - Secret Strike",               ('Stamp',             8,             14,                     0x009D)),
    ("Bowling 100-Pin (Stamp) - Pin Dropper",                 ('Hard Stamp',        8,             14,                     0x009E)),
    ("Bowling 100-Pin - Pro Status",                          ('Pro Status',        8,             14,                     0x009F)),
    #Bowling Spin Control
    ("Spin Control - First Strike",                           ('Custom',            8,             15,                     0x00A0)),
    ("Spin Control (Stamp) - One for All",                    ('Stamp',             8,             15,                     0x00A1)),
    ("Spin Control (Stamp) - Split Spare",                    ('Stamp',             8,             15,                     0x00A2)),
    ("Spin Control (Stamp) - Head First",                     ('Stamp',             8,             15,                     0x00A3)),
    ("Spin Control (Stamp) - English Major",                  ('Hard Stamp',        8,             15,                     0x00A4)),
    ("Spin Control (Stamp) - Pin Dropper",                    ('Hard Stamp',        8,             15,                     0x00A5)),
    ("Spin Control - Pro Status",                             ('Pro Status',        8,             15,                     0x00A6)),     
    #Power Cruising
    ("Power Cruising (Stamp) - Ringmaster",                   ('Stamp',             9,             16,                     0x00A7)),
    ("Power Cruising (Stamp) - 5,000-Pointer",                ('Long Stamp',        9,             16,                     0x00A8)),
    ("Power Cruising (Stamp) - Power Cruiser",                ('Hard Stamp',        9,             16,                     0x00A9)),
    ("Power Cruising (Stamp) - Power Jumper",                 ('Stamp',             9,             16,                     0x00AA)),
    ("Power Cruising (Stamp) - Leisure Cruiser",              ('Long Stamp',        9,             16,                     0x00AB)),
    ("Power Cruising - Pro Status",                           ('Pro Status',        9,             16,                     0x00AC)),
    #Canoeing
    ("Canoeing (Stamp) - Beginner License",                   ('Stamp',            10,             17,                     0x00AD)),
    ("Canoeing (Stamp) - Intermediate License",               ('Hard Stamp',       10,             17,                     0x00AE)),
    ("Canoeing (Stamp) - Expert License",                     ('Impossible Stamp', 10,             17,                     0x00AF)),
    ("Canoeing (Stamp) - Ducks in a Row",                     ('Stamp',            10,             17,                     0x00B0)),
    ("Canoeing (Stamp) - Cut the Red Tape",                   ('Impossible Stamp', 10,             17,                     0x00B1)),
    ("Canoeing - Pro Status",                                 ('Pro Status',       10,             17,                     0x00B2)),
    #Cycling
    ("Cycling - Complete Stage 1",                            ('Custom',           11,             18,                     0x00B3)),
    ("Cycling - Complete Stage 2",                            ('Custom',           11,             18,                     0x00B4)),
    ("Cycling - Complete Stage 3",                            ('Custom',           11,             18,                     0x00B5)),
    ("Cycling - Complete Stage 4",                            ('Custom',           11,             18,                     0x00B6)),
    ("Cycling - Complete Stage 5",                            ('Custom',           11,             18,                     0x00B7)),
    ("Cycling - Complete Stage 6",                            ('Custom',           11,             18,                     0x00B8)),
    ("Cycling (Stamp) - Last Gasp",                           ('Stamp',            11,             18,                     0x00B9)),
    ("Cycling (Stamp) - First of Many",                       ('Stamp',            11,             18,                     0x00BA)),
    ("Cycling (Stamp) - 1-Stage Master",                      ('Long Stamp',       11,             18,                     0x00BB)),
    ("Cycling (Stamp) - 3-Stage Master",                      ('Long Stamp',       11,             18,                     0x00BC)),
    ("Cycling (Stamp) - 6-Stage Master",                      ('Long Stamp',       11,             18,                     0x00BD)),
    ("Cycling - Pro Status",                                  ('Pro Status',       11,             18,                     0x00BE)),
    #Skydiving
    ("Skydiving (Stamp) - High Five",                         ('Stamp',            12,             19,                     0x00BF)),
    ("Skydiving (Stamp) - For the Birds",                     ('Hard Stamp',       12,             19,                     0x00C0)),
    ("Skydiving (Stamp) - Friends in High Places",            ('Stamp',            12,             19,                     0x00C1)),
    ("Skydiving (Stamp) - Camera Shy",                        ('Stamp',            12,             19,                     0x00C2)),
    ("Skydiving (Stamp) - 200-point Dive",                    ('Hard Stamp',       12,             19,                     0x00C3)),
    ("Skydiving - Pro Status",                                ('Pro Status',       12,             19,                     0x00C4)),
    #Island Flyover
    ("Island Flyover - Progressive I-Point Group (1)",        ('Custom',           12,             20,                     0x00C5)),
    ("Island Flyover - Progressive I-Point Group (2)",        ('Custom',           12,             20,                     0x00C6)),
    ("Island Flyover - Progressive I-Point Group (3)",        ('Custom',           12,             20,                     0x00C7)),
    ("Island Flyover - Progressive I-Point Group (4)",        ('Custom',           12,             20,                     0x00C8)),
    ("Island Flyover - Progressive I-Point Group (5)",        ('Custom',           12,             20,                     0x00C9)),
    ("Island Flyover - Progressive I-Point Group (6)",        ('Custom',           12,             20,                     0x00CA)),
    ("Island Flyover - Progressive I-Point Group (7)",        ('Custom',           12,             20,                     0x00CB)),
    ("Island Flyover - Progressive I-Point Group (8)",        ('Custom',           12,             20,                     0x00CC)),
    ("Island Flyover - Progressive I-Point Group (9)",        ('Custom',           12,             20,                     0x00CD)),
    ("Island Flyover - Progressive I-Point Group (10)",       ('Custom',           12,             20,                     0x00CE)),
    ("Island Flyover - Progressive I-Point Group (11)",       ('Custom',           12,             20,                     0x00CF)),
    ("Island Flyover - Progressive I-Point Group (12)",       ('Custom',           12,             20,                     0x00D0)),
    ("Island Flyover - Progressive I-Point Group (13)",       ('Custom',           12,             20,                     0x00D1)),
    ("Island Flyover - Progressive I-Point Group (14)",       ('Custom',           12,             20,                     0x00D2)),
    ("Island Flyover - Progressive I-Point Group (15)",       ('Custom',           12,             20,                     0x00D3)),
    ("Island Flyover - Progressive White Balloon Group (1)",  ('Custom',           12,             20,                     0x00D4)),
    ("Island Flyover - Progressive White Balloon Group (2)",  ('Custom',           12,             20,                     0x00D5)),
    ("Island Flyover - Progressive White Balloon Group (3)",  ('Custom',           12,             20,                     0x00D6)),
    ("Island Flyover - Progressive White Balloon Group (4)",  ('Custom',           12,             20,                     0x00D7)),
    ("Island Flyover - Progressive White Balloon Group (5)",  ('Custom',           12,             20,                     0x00D8)),
    ("Island Flyover - Progressive White Balloon Group (6)",  ('Custom',           12,             20,                     0x00D9)),
    ("Island Flyover - Progressive White Balloon Group (7)",  ('Custom',           12,             20,                     0x00DA)),
    ("Island Flyover - Progressive White Balloon Group (8)",  ('Custom',           12,             20,                     0x00DB)),
    ("Island Flyover - Progressive White Balloon Group (9)",  ('Custom',           12,             20,                     0x00DC)),
    ("Island Flyover - Progressive White Balloon Group (10)", ('Custom',           12,             20,                     0x00DD)),
    ("Island Flyover - Progressive White Balloon Group (11)", ('Custom',           12,             20,                     0x00DE)),
    ("Island Flyover (Stamp) - Island Hopper",                ('Stamp',            12,             20,                     0x00DF)),
    ("Island Flyover (Stamp) - Pop Frenzy",                   ('Hard Stamp',       12,             20,                     0x00E0)),
    ("Island Flyover (Stamp) - Follow That Plane",            ('Stamp',            12,             20,                     0x00E1)),
    ("Island Flyover (Stamp) - Wuhu Tour Guide",              ('Impossible Stamp', 12,             20,                     0x00E2)),
    ("Island Flyover (Stamp) - Balloonatic",                  ('Impossible Stamp', 12,             20,                     0x00E3))
])                     

location_sort_order = {
    loc: i for i, loc in enumerate(location_table.keys())
}

location_groups = {
    'Stamp': [name for (name, data) in location_table.items() if data[0] == 'Stamp' or data[0] == 'Hard Stamp' or data[0] == 'Long Stamp' or data[0] == 'Impossible Stamp'],
    'Normal Stamp': [name for (name, data) in location_table.items() if data[0] == 'Stamp'],
    'Hard Stamp': [name for (name, data) in location_table.items() if data[0] == 'Hard Stamp'],
    'Impossible Stamp': [name for (name, data) in location_table.items() if data[0] == 'Impossible Stamp'],
    'Long Stamp': [name for (name, data) in location_table.items() if data[0] == 'Long Stamp'],
    'Pro Status': [name for (name, data) in location_table.items() if data[0] == 'Pro Status'],
    'Champion': [name for (name, data) in location_table.items() if data[0] == 'Champion'],
    'Difficulty': [name for (name, data) in location_table.items() if data[0] == 'Difficulty'],
    'iPoint': [name for (name, data) in location_table.items() if data[0] == 'iPoint'],
    'Custom': [name for (name, data) in location_table.items() if data[0] == 'Custom'],
}