from BaseClasses import Location


class WSRLocation(Location):
    game: str = "Wii Sports Resort"


GLOBAL_LOCATIONS = {}

SWF_VS_LOCATIONS = {}
SWF_PRC_LOCATIONS = {}
SWF_SGL_LOCATIONS = {}

WKB_LOCATIONS = {}

FLD_LOCATIONS = {}

DGL_LOCATIONS = {}

ARC_LOCATIONS = {}

BSK_3PT_LOCATIONS = {}
BSK_VS_LOCATIONS = {}

PNG_VS_LOCATIONS = {}
PNG_RET_LOCATIONS = {}

GLF_LOCATIONS = {}

BWL_STD_LOCATIONS = {}
BWL_100_LOCATIONS = {}
BWL_WAL_LOCATIONS = {}

JSK_LOCATIONS = {}

CAN_LOCATIONS = {}

BIC_LOCATIONS = {}

PLN_LOCATIONS = {}

OMK_LOCATIONS = {}

HARD_STAMPS_LOCATIONS = {}

LONG_STAMPS_LOCATIONS = {}



location_table = {
    **GLOBAL_LOCATIONS
    **SWF_VS_LOCATIONS
    **SWF_PRC_LOCATIONS
    **SWF_SGL_LOCATIONS
    **WKB_LOCATIONS
    **FLD_LOCATIONS
    **DGL_LOCATIONS
    **ARC_LOCATIONS
    **BSK_3PT_LOCATIONS
    **BSK_VS_LOCATIONS
    **PNG_VS_LOCATIONS
    **PNG_RET_LOCATIONS
    **GLF_LOCATIONS
    **BWL_STD_LOCATIONS
    **BWL_100_LOCATIONS
    **BWL_WAL_LOCATIONS
    **JSK_LOCATIONS
    **CAN_LOCATIONS
    **BIC_LOCATIONS
    **PLN_LOCATIONS
    **OMK_LOCATIONS
}